__base__: ../../metrics/classification.yaml

data:
    class_path: lightning_template.LightningDataModule
    init_args:
        dataset_cfg:
            split_info:
                split_format_to: [ann_file]
            fit:
                class_path: datasets.MITBIHDataset
                init_args:
                    ann_file: ${split}.txt
                    data_root: data/mit-bih-arrhythmia-database-1.0.0
                    ecg_process_method: dwt
        dataloader_cfg:
            batch_size: 32
            # num_workers: 8
            # persistent_workers: true
            prefetch_factor: 2
            pin_memory: true
