__base__:
    - ../../default_runtime.yaml
    - ../../schedules/schedule_60e.yaml
    - ../../datasets/tianchi/tianchi_round_1_multi_label.yaml
    - ../../models/conv_transformer_language_model/conv_transformer_language_model_multi_label.yaml
    - ../../datasets/tianchi/tianchi_round_1_model_num_classes.yaml

model:
    init_args:
        model:
            init_args:
                signal_kind_num: 12
