__base__:
    - ../../default_runtime.yaml
    - ../../schedules/schedule_1x.yaml
    - ../../datasets/tianchi/tianchi_multi_label.yaml
    - ../../models/conv_clep/conv_clep_multi_label.yaml
    - ../../datasets/tianchi/model_num_classes.yaml

model:
    init_args:
        model:
            init_args:
                symbols:
                    - QRS低电压
                    - QT间期延长
                    - ST-T改变
                    - ST段改变
                    - T波改变
                    - 一度房室传导阻滞
                    - 下壁异常Q波
                    - 不完全性右束支传导阻滞
                    - 临界ECG
                    - 二联律
                    - 前间壁R波递增不良
                    - 双分支传导阻滞
                    - 右心室肥大
                    - 右心房扩大
                    - 右束支传导阻滞
                    - 复极化异常
                    - 完全性右束支传导阻滞
                    - 完全性左束支传导阻滞
                    - 室上性早搏
                    - 室内差异性传导
                    - 室性早搏
                    - 左前分支传导阻滞
                    - 左心室肥大
                    - 左心室高电压
                    - 左束支传导阻滞
                    - 差异性传导
                    - 异常ECG
                    - 心房颤动
                    - 快室率心房颤动
                    - 快心室率
                    - 慢心室率
                    - 房室传导延缓
                    - 房性早搏
                    - 早期复极化
                    - 未下传的房性早搏
                    - 正常ECG
                    - 电轴右偏
                    - 电轴左偏
                    - 短PR间期
                    - 短串房性心动过速
                    - 窦性心动过缓
                    - 窦性心动过速
                    - 窦性心律
                    - 窦性心律不齐
                    - 肺型P波
                    - 肺心病型
                    - 融合波
                    - 起搏心律
                    - 逆钟向转位
                    - 非特异性ST段与T波异常
                    - 非特异性ST段异常
                    - 非特异性T波异常
                    - 非特异性室内传导延迟
                    - 非特异性室内传导阻滞
                    - 顺钟向转位
                symbol_embedding_path: data/tianchi/symbols_chatgpt/symbol_embedding.pkl
                signal_kind_num: 12
