__base__:
    - ../../default_runtime.yaml
    - ../../schedules/schedule_1x.yaml
    - ../../datasets/tianchi/tianchi_round_1_multi_label.yaml
    - ../../models/conv_transformer_with_channel/conv_transformer_with_channel_multi_label.yaml
    - ../../datasets/tianchi/tianchi_round_1_model_num_classes.yaml

model:
    init_args:
        model:
            init_args:
                conv:
                    init_args:
                        in_channels: 12
                signal_kind_num: 12
