model:
    init_args:
        evaluator_cfg:
            class_path: torchmetrics.MetricCollection
            init_args:
                metrics:
                    - class_path: torchmetrics.Accuracy
                      init_args:
                          task: multilabel
                          num_labels: 4
                    - class_path: torchmetrics.F1Score
                      init_args:
                          task: multilabel
                          num_labels: 4
                    - class_path: torchmetrics.AveragePrecision
                      init_args:
                          task: multilabel
                          num_labels: 4
                    - class_path: torchmetrics.AUROC
                      init_args:
                          task: multilabel
                          num_labels: 4
                    - class_path: torchmetrics.ClasswiseWrapper
                      init_args:
                          labels: [L, R, V, A]
                          metric:
                              class_path: torchmetrics.Accuracy
                              init_args:
                                  task: multilabel
                                  num_labels: 4
                    - class_path: torchmetrics.ClasswiseWrapper
                      init_args:
                          labels: [L, R, V, A]
                          metric:
                              class_path: torchmetrics.F1Score
                              init_args:
                                  task: multilabel
                                  num_labels: 4
                    - class_path: torchmetrics.ClasswiseWrapper
                      init_args:
                          labels: [L, R, V, A]
                          metric:
                              class_path: torchmetrics.AveragePrecision
                              init_args:
                                  task: multilabel
                                  num_labels: 4
                    - class_path: torchmetrics.ClasswiseWrapper
                      init_args:
                          labels: [L, R, V, A]
                          metric:
                              class_path: torchmetrics.AUROC
                              init_args:
                                  task: multilabel
                                  num_labels: 4

trainer:
    callbacks:
        change_item:
            - - 0
              - init_args:
                    monitor: val/MultilabelF1Score
                    filename: "epoch:{epoch}-val_f1:{val/MultilabelF1Score:.4g}.ckpt"
                    mode: max
