__base__: ./classification.yaml

model:
    init_args:
        evaluator_cfg:
            init_args:
                metrics:
                    acc:
                        init_args:
                            task: multilabel
                            num_labels: 4
                    F1:
                        init_args:
                            task: multilabel
                            num_labels: 4
                    PR-AUC:
                        init_args:
                            task: multilabel
                            num_labels: 4
                    ROC-AUC:
                        init_args:
                            task: multilabel
                            num_labels: 4
