__base__:
    - ../../default_runtime.yaml
    - ../../schedules/schedule_60e.yaml
    - ../../datasets/tianchi/tianchi_round_all_multi_label.yaml
    - ../../models/resnet1d_with_channel/resnet1d50_with_channel_multi_label.yaml
    - ../../datasets/tianchi/tianchi_round_all_model_num_classes.yaml
