model:
    class_path: lightning_template.LightningModule
    init_args:
        model:
            class_path: models.ResNet1D
            init_args:
                arch: res18
                num_classes: 3
