__base__:
    - ../../default_runtime.yaml
    - ../../schedules/schedule_1x.yaml
    - ../../datasets/mit_bih/mit_bih_multi_label.yaml
    - ../../models/conv_transformer/conv_transformer_multi_label.yaml
