__base__: tianchi_round_all_multi_label.yaml

data:
    init_args:
        dataloader_cfg:
            batch_size: 2

model:
    init_args:
        evaluator_cfg:
            class_path: torchmetrics.MetricCollection
            init_args:
                metrics:
                    __delete__: true
                    bleu:
                        class_path: torchmetrics.BLEUScore

trainer:
    logger:
        init_args:
            tags:
                pre_item:
                    - language_model
                    - tianchi
                    - round_all
    callbacks:
        change_item:
            - - 0
              - init_args:
                    monitor: val/bleu
                    filename: "epoch:{epoch}-val_bleu:{val/bleu:.4g}.ckpt"
                    mode: max
