__base__:
    - ../../default_runtime.yaml
    - ../../schedules/schedule_1x.yaml
    - ../../datasets/tianchi/tianchi_multi_label.yaml
    - ../../models/resnet1d/resnet1d34_multi_label.yaml

model:
    init_args:
        model:
            init_args:
                num_classes: 55
