__base__:
    - ../../default_runtime.yaml
    - ../../schedules/schedule_30x.yaml
    - ../../datasets/tianchi/tianchi_multi_label.yaml
    - ../../models/resnet1d/resnet1d9_multi_label.yaml
    - ../../datasets/tianchi/model_num_classes.yaml
