__base__:
    - ../../default_runtime.yaml
    - ../../schedules/schedule_1x.yaml
    - ../../datasets/tianchi/tianchi_multi_label.yaml
    - ../../models/clep/clep_multi_label.yaml

model:
    init_args:
        model:
            init_args:
                symbol_embedding_path: data/tianchi/symbols_chatgpt/symbol_embedding.pkl
