__base__:
    - ../../default_runtime.yaml
    - ../../schedules/schedule_1x.yaml
    - ../../datasets/tianchi/tianchi_multi_label.yaml
    - ../../models/clep/ecg_transformer_multi_label.yaml

model:
    init_args:
        model:
            init_args:
                signal_kind_num: 12
                num_classes: 55
