model:
    class_path: lightning_template.LightningModule
    init_args:
        model:
            class_path: models.ResNet1DWithChannel
            init_args:
                arch: res18
                in_channels: 2
                num_classes: 3
