__base__: ./ecg_transformer.yaml

model:
    init_args:
        model:
            class_path: models.CLEP
            init_args:
                normalize_loss: false
                symbol_embedding_dim: 1536
                symbol_embedding_path: data/mit-bih-arrhythmia-database-1.0.0/symbols/symbol_embedding.pkl
